import Navbar from '@/components/Navbar'
import { Inter } from 'next/font/google'
import './global.css';

// If loading a variable font, you don't need to specify the font weight
const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en" className={inter.className}>
      <body className='w-full min-h-screen'>
        <Navbar />
        {children}
      </body>
    </html>
  )
}
